# Configuración de Netlify para la webApp STADR.

[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200
  force = true

[[redirects]]
  from = "/api/store"
  to = "/.netlify/functions/store"
  status = 200
  force = true

[[redirects]]
  from = "/api/check"
  to = "/.netlify/functions/check"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
